### ISSUE TITLE
Mac looks wack 

### ISSUE THREAD

**Issue by StealthHydra179** [MCPI-Devs/MCPIL-R#3]
![Screen Shot 2020-12-08 at 7 57 26 PM](https://user-images.githubusercontent.com/47306082/101560037-66efd680-3990-11eb-94b8-bdcf6c4d2ef5.png)

**Comment by Alvarito050506** [comment]
I think this is TKinter-Mac's problem... And anyways you cannot use MCPIL-R in Macs so... Closing this.
