### ISSUE TITLE
TK deprecation

### ISSUE THREAD

**Issue by StealthHydra179** [MCPI-Devs/MCPIL-R#6]
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

**Comment by Alvarito050506** [comment]
Again, it looks like a Mac-specific problem, which is not currently supported by MCPIL-R. Anyways, TKInter is enumerated in the package dependencies.
